language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - python dbdb/setup.py install

script:
  - pytest

deploy:
  - provider: heroku
    api_key: 
      secure: $HEROKU_API_KEY
    app: dbdb-todo-flask